{% set name = "evomsa" %}
{% set version = "1.9.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/EvoMSA-{{ version }}.tar.gz
  sha256: 7b8a22d2e4794b181a94b6cf336723b48e2671af8f05c4abbc6f105503dd6d45

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - numpy
    - pip
    - python
  run:
    - b4msa
    - evodag
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - EvoMSA
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ingeotec/EvoMSA
  summary: Sentiment Analysis System based on B4MSA and EvoDAG
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mgraffg
