{% set name = "evomsa" %}
{% set version = "2.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/EvoMSA-{{ version }}.tar.gz
  sha256: 0fcaf6ad5cdd480322d81eec1a3039d19dd83286a77b544f83ecca30e7df7147

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - cython
    - numpy
    - pip
    - python
  run:
    - b4msa
    - evodag
    - python

test:
  imports:
    - EvoMSA
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ingeotec/EvoMSA
  summary: Sentiment Analysis System based on B4MSA and EvoDAG
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mgraffg
