{% set name = "evomsa" %}
{% set version = "1.9.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/EvoMSA-{{ version }}.tar.gz
  sha256: b94dce2a064e0f75a67dd00de0b651d637f5c0ce4e38a71a58eafe381def1b1d

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - numpy
    - pip
    - python
  run:
    - b4msa
    - evodag
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - EvoMSA
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ingeotec/EvoMSA
  summary: Sentiment Analysis System based on B4MSA and EvoDAG
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mgraffg
