{% set name = "evomsa" %}
{% set version = "2.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2940442036f62d51a8ad9f62c0c4f93f02494b16e684e0c1aca4bda58409a5da

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - setuptools
    - cython
    - numpy
    - pip
    - python
  run:
    script: python -m pip install jax
    - b4msa
    - evodag
    - python
    - ingeoml >=0.0.25

test:
  imports:
    - EvoMSA
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ingeotec/EvoMSA
  summary: Sentiment Analysis System based on B4MSA and EvoDAG
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mgraffg
