{% set name = "evomsa" %}
{% set version = "2.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 69b0344178173a39452844146f8f2be00c8e3c70519f3df3038390229796c911

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - cython
    - numpy
    - pip
    - python
  run:
    - b4msa
    - evodag
    - python

test:
  imports:
    - EvoMSA
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ingeotec/EvoMSA
  summary: Sentiment Analysis System based on B4MSA and EvoDAG
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mgraffg
